### ISSUE TITLE
vaadin-list-box is not working with paper-menu-button

### ISSUE THREAD

**Issue by hyyan** [vaadin/vaadin-list-box#47]
Hi,

It is not possible to use `vaadin-list-box` with `paper-menu-button`, the menu is not closed once an item is selected.

It seems `paper-menu-button` listens to specific event `iron-select` to auto close the menu.
vaadin-list-box should fire the same event to be compatible with polymer components.

**Comment by tomivirkki** [comment]
Hi, the Vaadin Components don't aim to be 100% compatible with Paper components. In fact, we're planning to gradually reduce our dependencies to Polymer's modules in the near future. In order to get `iron-select` event fired, you'll need wire it programmatically, something like:
```js
listBox.addEventListener('selected-changed',
e => e.currentTarget.dispatchEvent(new CustomEvent('iron-select')));
```

**Comment by hyyan** [comment]
@tomivirkki Thanks for your answer.
IMHO , this `iron-select` event can be fired inside the component itself, this will have no impact on the performance or the code complexity or what so ever. this will make the life of developers who use this component easier instead of forcing us to add a hack here and there to make things work. 
I just do not understand the strategy of vaadin developers at all, anyway, this is not the right place for discussion.

**Comment by web-padawan** [comment]
> I just do not understand the strategy of vaadin developers at all, anyway, this is not the right place for discussion.

Some Vaadin components have *some* built-in support for Paper elements:
- you can place `paper-input` into `vaadin-combo-box-light`
- you can place `paper-listbox` into `vaadin-context-menu`

Back in 2016, we did not have a comprehensive set of components and at that time we used to build on top of Paper elements (e. g. version 1.x of `vaadin-combo-box` and `vaadin-date-picker`). 

This has changed with the Vaadin platform release. And we do not encourage using Iron and Paper elements anymore because of the fact that they are currently in maintenance.

**Comment by tomivirkki** [comment]
It also makes more sense for us to adhere to standards rather than to compatibility with "component library X". Even Google's own next generation [Material Components](https://github.com/material-components/material-components-web) don't seem to aim for compatibility with Paper components.
